project_name: statuspage.io-maintenance-cli

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: general
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - freebsd

  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  -
    repository:
      owner: justinas-b
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:  # Git author used to commit to the repository.
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"  # The project name and current git tag are used in the format string.
    folder: Formula  # Folder inside the repository to put the formula.

    description: "CLI tool to interact with statuspage.io and set maintenance on multiple pages at once"
    caveats: "./statuspage.io-maintenance-cli -apiKeys abcd1234,efgh5678"  # Caveats for the user of your binary.
    homepage: "https://github.com/justinas-b/statuspage.io-maintenance-cli" # Your app's homepage.
    test: |
      system "#{bin}/statuspage.io-maintenance-cli -h"
    install: |
      bin.install "statuspage.io-maintenance-cli"